import { VT323 } from 'next/font/google'
import './globals.css'

const inter = VT323({ subsets: ['latin'],
weight:'400'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-950`}>{children}</body>
    </html>
  )
}
